version: 1.0.{build}
image: Ubuntu
build_script:
- sh: sudo apt-get update && sudo apt-get install -y sudo git gcc g++ build-essential cmake uuid-dev && sudo rm -rf /var/lib/apt/lists/*
- sh: git submodule update --init --recursive
- sh: cd tests/cmocka && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr .. && make && sudo make install && cd ../../..
test_script:
- sh: sudo bash -eo pipefail run-tests.sh
