version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: 'apt-get update && apt-get install -y sudo git gcc g++ build-essential cmake uuid-dev bash curl && rm -rf /var/lib/apt/lists/* && git submodule update --init --recursive'
      - run:
          name: Build cmocka
          command: 'cd tests/cmocka && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/usr .. && make && sudo make install && cd ../../..'
      - run:
          name: Build and run tests
          command: 'bash run-tests.sh'
      - run:
          name: Upload coverage reports
          when: on_success
          command: cd build/CMakeFiles/glitchedhttps.dir/src && bash <(curl -s https://codecov.io/bash)
