version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: 'apt-get update && apt-get install -y sudo git gcc g++ build-essential cmake uuid-dev && rm -rf /var/lib/apt/lists/* && git submodule update --init --recursive'
      - run:
          name: Build and run tests
          command: 'bash run-tests.sh'
